### ISSUE TITLE
Issue upload file

### ISSUE THREAD

**Issue by eltonf1** [damienbod/WebApiFileUpload#2]
I got the project and opened on VS and I'm trying to test his code, but when I click on "Upload" button, I got an error, like:

> This site can’t be reached
> 
> localhost refused to connect.
> Search Google for localhost 8081 api test files
> ERR_CONNECTION_REFUSED

Do I need to configure/adjust anything on code to reach the api?

Thanks.

**Comment by eltonf1** [comment]
I got the problem and I fixed it. I'm missing to start the API server.

**Comment by damienbod** [comment]
cool Greetings Damien
